### ISSUE TITLE
Feat: Add support for Emoji Log commit standard

### ISSUE THREAD

**Issue by michaelborn** [elpete/commandbox-semantic-release#8]
The commits generated by tools like [Emoji Log](https://marketplace.visualstudio.com/items?itemName=ahmadawais.emoji-log-vscode) do not _necessarily_ conform to the conventional commit standard. Yet... they're awfully close!

![demonstration of Emoji Log VS Code Plugin](https://raw.githubusercontent.com/ahmadawais/Emoji-Log-VSCode/master/images/emoij-log.gif)

Here's a list of potential Emoji Log commits

1. `📦 NEW: IMPERATIVE_MESSAGE_GOES_HERE`
    > Use when you add something entirely new.
    > E.g. `📦 NEW: Add Git ignore file`

1. `👌 IMPROVE: IMPERATIVE_MESSAGE_GOES_HERE`
    > Use when you improve/enhance piece of code like refactoring etc.
    > E.g. `👌 IMPROVE: Remote IP API Function`

1. `🐛 FIX: IMPERATIVE_MESSAGE_GOES_HERE`
    > Use when you fix a bug — need I say more?
    > E.g. `🐛 FIX: Case conversion`

1. `📖 DOC: IMPERATIVE_MESSAGE_GOES_HERE`
    > Use when you add documentation like `README.md`, or even inline docs.
    > E.g. `📖 DOC: API Interface Tutorial`

1. `🚀 RELEASE: IMPERATIVE_MESSAGE_GOES_HERE`
    > Use when you release a new version.
    > E.g. `🚀 RELEASE: Version 2.0.0`

1. `🤖 TEST: IMPERATIVE_MESSAGE_GOES_HERE`
    > Use when it's related to testing.
    > E.g. `🤖 TEST: Mock User Login/Logout`

1. `‼️ BREAKING: IMPERATIVE_MESSAGE_GOES_HERE`
    > Use when releasing a change that breaks previous versions.
    > E.g. `‼️ BREAKING: Change authentication protocol`

_— That's it for now. Nothing more nothing less._

Would implementing a `EmojiLogCommitParser.cfc` plugin component be enough to support the Emoji Log standard?

**Comment by elpete** [comment]
> Would implementing a EmojiLogCommitParser.cfc plugin component be enough to support the Emoji Log standard?

This is the way I'd go about it.  Once you have one you are happy with, I'm fine adding it as an option here in this library.
